<?php

namespace App\Repository;

use App\Entity\IngredientDisplayPreferenceOverride;
use Doctrine\ORM\EntityRepository;

/**
 * IngredientDisplayPreferenceOverrideRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class IngredientDisplayPreferenceOverrideRepository extends EntityRepository
{

    /**
     * @return IngredientDisplayPreferenceOverride[]
     */
    public function getAllCommon()
    {
        $qb = $this->createQueryBuilder('ridp');
        $qb->andWhere('ridp.author is null');

        return $qb->getQuery()
            ->getResult();
    }
}
