<?php

namespace App\Repository;

use App\Entity\RefIngredientDisplayPreference;
use Doctrine\ORM\EntityRepository;

/**
 * RefIngredientDisplayPreferenceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RefIngredientDisplayPreferenceRepository extends EntityRepository
{

}
