<?php

namespace App\URLParser;

use App\Entity\Recipe;
use PHPHtmlParser\Dom;

class URLParserChefkoch extends URLParserBase
{
    /**
     * @inheritDoc
     */
    public function readSingleRecipeFromUrl(Recipe $recipe, $url)
    {
        $dom = new Dom;
        $dom->loadFromUrl($url);
        $title = $dom->find('h1.page-title', 0)->text;
        if ($title != '') {
            $recipe->setTitle($title);
        }
        $recipe->setSummary($dom->find('div.summary', 0)->text);
        $ingredientsTable = $dom->find('table.ingredients', 0);

        $preparation = $dom->find('div #rezept-zubereitung', 0)->innerHtml;

        dump($preparation);die;

        return parent::readSingleRecipeFromUrl($recipe, $url); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function canHandleUrl($url)
    {
        $parts = parse_url($url);

        if ($parts['host'] != 'www.chefkoch.de' && $parts['host'] != 'chefkoch.de') {
            return false;
        }

        if (preg_match('/^\/rezepte\/*/',$parts['path']) !== 1) {
            return false;
        }

        return true;
    }

}
